### ISSUE TITLE
Spookcity_Kernel-N

### ISSUE THREAD

**Issue by Spookcity** [Spookcity/ROMS-G800F#12] opened 2017-04-22 19:52 UTC
Just a place to share your experiences with the kernel. Let me know about any bugs or problems you experience. Also share any features you may want to see included in future builds.
[Git repo](https://github.com/Spookcity/android_kernel_samsung_kminilte/tree/N_custom)
[XDA thread](https://forum.xda-developers.com/galaxy-s5-mini/orig-development/kernel-cm13-custom-kernel-t3386508) (Although I may create a new one for the Nougat kernel. I'm still unsure of the best route to go)
[Test builds will be posted here](https://github.com/Spookcity/ROMS-G800F/issues/10)

**Comment by ghost** [comment] 2017-04-22 20:01
Thanks for posting it here too! I hope you didn't find it too unreasonable.

As for the new XDA thread: I'd definitely create a new one, just for the sake of clarity. But as you may have noticed, I may be exaggerating the clarity a bit too much ;).

I'm so sorry that I can't test the kernel, but I've fallen in love (sort of) with XOSP and I'm not using Nougat at the moment. I do switch ROMs often so I might be using Nougat some time next week so I'll try it out then. However, I have been using XOSP for 8 days already, which is almost a new record for me.

By the way: should I reference people on XDA at the thread for your kernel to this thread so they can stay informed for new test builds?

**Comment by Spookcity** [comment] 2017-04-22 20:08
@StanNL No,not unreasonable at all. I'm still trying to figure out this system a little,but I do like it and its a good idea! 
I have already referenced the test build on the XDA thread,so hopefully some people can try it out and let me know if all is OK.

Maybe XOSP Nougat will come to our device soon! You said nico_vo was going to work on it if I'm not mistaken. If not, I will give it a go after I try to build CosmicOS.

**Comment by ghost** [comment] 2017-04-22 20:20
@Spookcity
> No,not unreasonable at all. I'm still trying to figure out this system a little,but I do like it and its a good idea!

That's great, thanks! By the way: I always use FastHub on my phone which is a beautiful ~~XDA~~  (edit: I meant __GitHub__ ) app. It wouldn't work for posting builds of course since you still have to do those from your PC, but when posting comments it works great! (By the way: it isn't available through Google Play atm due to copyright issues, so you'll have to install it through GitHub via your browser, you can find it [here](https://github.com/k0shk0sh/FastHub)
)

> I have already referenced the test build on the XDA thread,so hopefully some people can try it out and let me know if all is OK. 

Oh I didn't even notice, but that's the whole problem with XDA, because you have to check everything manually and you don't get notifications (unless you get quoted). That's what this is for!

> Maybe XOSP Nougat will come to our device soon! You said nico_vo was going to work on it if I'm not mistaken. If not, I will give it a go after I try to build CosmicOS.

Ooh that would be great! Nico indeed tried it after he installed Linux. However, he had an error while downloading sources. He told me he was going to ask you last week, but I think he's too hesitant (or he's too busy).

**Comment by Oleggluk** [comment] 2017-04-23 09:07
The new kernel works well for RR N 5.8.2.
I want to see, voltage control, various governors, lowering the minimum frequency. (Google Translate)

**Comment by Spookcity** [comment] 2017-04-23 09:12
@Oleggluk All of these features are planned and most should be fairly easy to achieve. I plan to try voltage control as well,but I need to look into this some as I'm a little unsure how to implement it and I don't want to cause major problems!
At this point I'm just really glad that I set up anykernel2 properly :D

**Comment by Oleggluk** [comment] 2017-04-23 09:19
I'm ready to test any attempts to change the voltage, even to break my phone)) (Google translation)

**Comment by Spookcity** [comment] 2017-04-23 09:24
Thank you @Oleggluk. I will test first though as I would feel really bad if my kernel destroyed anyone's phone. Hopefully I'll have some time this week to research voltage control some and see what happens.

**Comment by AndiVR46** [comment] 2017-04-24 17:12
Hi , i tested the Kernel N in Lineage OS 14.1 since saturday - no issues so far

![kernel](https://cloud.githubusercontent.com/assets/27836686/25349379/e8b33ae6-2921-11e7-936c-57e8517a0acb.PNG)

**Comment by Spookcity** [comment] 2017-04-24 18:24
@AndiVR46 Good news and thanks for the feedback! There is one issue that was pointed out to me and that I also have....Recorded audio is very distorted. I'm going to try to look into this soon.
I've only tested this on AEX and I'm unsure what Rom the other person who experienced this was using,but if you get a chance, test this out for me. I'm nearly positive it's not ROM specific,but still wanna be 100%

**Comment by AndiVR46** [comment] 2017-04-24 18:46
i can confirm  it... The recorded sound is very scratchy at mine, but at my GFs S5mini (LOS 14.1) with the ,,old'' kernel 3.4.39+ sounds CLEAR ;)

**Comment by Spookcity** [comment] 2017-04-24 18:53
Thanks a lot for testing. I figured as much. More than likely this going to be caused by one of the MANY Linux kernel patches I applied. I'm going to try to disable a few flags in the build. Use a different toolchchain to see if that fixes it before I go slowly over all of those kernel patches. That'll be fun lol

**Comment by AndiVR46** [comment] 2017-04-24 19:17
with pleasure... hope you can fix it.

**Comment by Oleggluk** [comment] 2017-04-26 13:29
I found a very serious problem! After some applications (games), the smartphone does not see the headphones and outputs the sound through an external speaker. The same problem was previously at the core of DJ_Steve, he could not solve it. (Google Translate)

**Comment by Spookcity** [comment] 2017-04-26 14:16
@Oleggluk Thank you for letting me know.  So strange. It almost has to be related to the Linux kernel patches. I thought that I solved that on my previous kernel build for MM ROMS by replacing one particular file. Hopefully I can do the same this time around.  If  not and it is caused by the kernel patches, I may just release a kernel, for the time being without the patches, so it would still be 3.4.39.
Hopefully I'll have some time this weekend to mess around with it and try to figure out what's going on.

**Comment by AshVo925** [comment] 2017-04-26 20:20
I finally got this rom on after slim6 but am hoping not to regret it,so far i actually kinda love this rom,will update as it happens

**Comment by Spookcity** [comment] 2017-04-27 06:25
@AshVo925 Hey thanks for joining in!  I'm a bit unsure,but I think you're speaking of slim 7 as I remember you posting in that thread.  If so, I don't think you'll regret it. It's a nice ROM and I never noticed any major issues with it. Hope it works out for you!

**Comment by ghost** [comment] 2017-05-02 08:50
I'll install the new kernel, now that I'm using XOSP 7.1. However, are there any real benefits at this point?

**Comment by Spookcity** [comment] 2017-05-02 09:03
@StanNL Yeah,there should be. Even though I've yet to add any features, I've patched the Linux kernel (to 3.4.105 in this build) I've added many optimization flags to the build and I've built it with my ct-ng build of Uber toolchain,so it should hopefully be at least a little "snappier"

Also, there is a huge benefit for me as I really want to make sure there's no issues with just the patches,toolchain and optimizations before I start adding things :D

**Comment by ghost** [comment] 2017-05-02 09:10
@Spookcity Alright, thanks for the update! Good luck with adding the features you want.

**Comment by AndiVR46** [comment] 2017-05-02 09:20
Hi, i test the new 3.4.105 Kernel with LOS 14.1 build of zytrix78 (7.1.2), the recorded audio issue seems to be solved when i compare the audio of my GFs 3.4.39 one with mine...

**Comment by Spookcity** [comment] 2017-05-02 09:30
@AndiVR46 Thanks a lot for the feedback! I really hope that's the case. My recorded audio also is good,but who knows. This will make it a lot easier if all of the audio issues are solved in this build cause then I know it's one of the last 8 Linux patches,as opposed to trying to sort through 60+ patches!

**Comment by Oleggluk** [comment] 2017-05-08 11:33
Hey. For a long time I wanted to ask how to fix this error. Battery stats service no controller energy info supplied.
This is on all custom firmware of our device. Can some file not be properly configured or missing? (Google Translate) 
![screenshot_20170508-140744](https://cloud.githubusercontent.com/assets/27913216/25802480/43c54062-33fb-11e7-8344-b8fa872eba15.png)

**Comment by Spookcity** [comment] 2017-05-08 12:59
@Oleggluk I think that is the case yeah. I'm not positive,but I believe that it's related to a power_profiles.xml.

**Comment by Oleggluk** [comment] 2017-05-08 13:01
Where is he located? Can it be edited or extracted from the original firmware?

**Comment by Spookcity** [comment] 2017-05-08 13:10
@Oleggluk I think its part of the framework. You would have to use apktool to decompile the framework.res and pull the power_profile from there. Then you could edit it. And recompile the framework. I think there may be something related in the kernel as well,but I believe this error is due to the devices.

**Comment by Oleggluk** [comment] 2017-05-08 13:22
I decompiled framework.res, there is such a file there. It is he?

Here you can not use this format, put it in the archive.
[power_profile.zip](https://github.com/Spookcity/ROMS-G800F/files/983568/power_profile.zip)

**Comment by Spookcity** [comment] 2017-05-08 13:26
@Oleggluk I can't see that file,but its probably correct. I think it should be located with framework/res/res/xml/power_profile.xml
I can't help much with what to edit to fix this though. I've never looked into really.

**Comment by Oleggluk** [comment] 2017-05-08 13:34
I pulled the same file from the original 6.0.1, they are identical. Any other ideas?

**Comment by Spookcity** [comment] 2017-05-08 13:52
@Oleggluk Hmm,interesting. Not off hand. I'll have to think a little. I'll let you know if I come up with any.

**Comment by Oleggluk** [comment] 2017-05-10 10:01
There is an interesting topic. https://forum.xda-developers.com/android/apps-games/app-spectrum-kernel-manager-users-t3601542 . Maybe you should try adding to the kernel? (Google Translate)

**Comment by Spookcity** [comment] 2017-05-10 10:50
@Oleggluk Interesting. Thanks,I'm always happy to get ideas and suggestions. Especially with a link. I will look more into that when I get home later. I've been working on adding synapse support to my kernel,which I've been able to do. Getting the backend setup so it works properly may be another story. I'm just not sure how much time I want to spend on it. We shall see.

**Comment by Spookcity** [comment] 2017-05-10 14:33
@Oleggluk [Here you go](https://github.com/Spookcity/ROMS-G800F/issues/10#issuecomment-300500982)

**Comment by Oleggluk** [comment] 2017-05-16 15:15
"Kernel su-hide," is this going to help pass security? (Google Translate)
https://www.xda-developers.com/lineageos-change-log-9-jelly-as-the-default-browser-kernel-su-hide-and-more/

**Comment by Spookcity** [comment] 2017-05-16 16:07
@Oleggluk I don't believe so as Magisk hide seems to work on some other devices. There is a kernel patch by sultanxda that also has helped many other devices pass. I tried and it didn't work. I will look a bit more at that link though.
 
Edit: 
If I can find the kernel patch I will add it to my kernel build though if I'm able as it does help with security. 

Edit2:
[This is the patch](https://review.lineageos.org/#/c/170648/)
I'll try to patch and build tonight or tomorrow and see the outcome.

**Comment by Oleggluk** [comment] 2017-05-17 17:34
@Spookcity This kernel supports zRam? And how to set it up? (Google Translate)

**Comment by Spookcity** [comment] 2017-05-17 17:53
@Oleggluk I have not done or set up anything with zram. I believe I can do this as a init patch inside anykernel2 though. I will look more into it. I had it planned anyway. Maybe next test build.

**Comment by Oleggluk** [comment] 2017-05-23 11:42
Kernel test6, did anyone notice strangeness with charging? The phone is faster charging.

**Comment by Spookcity** [comment] 2017-05-23 12:11
@Oleggluk I have not noticed that,but I will try to pay closer attention and see..Better faster than slower though, right? :D

**Comment by Oleggluk** [comment] 2017-05-23 12:38
@Spookcity Fast charging is good. The main thing is not to discharge quickly. I'll watch it. Is there news about the new TWRP?

**Comment by Spookcity** [comment] 2017-05-23 12:44
@Oleggluk Indeed! As far as TWRP,if ayke doesn't have a new build out sometime soon and I have the time I will try to build an update.

**Comment by Oleggluk** [comment] 2017-05-24 12:13
Unfortunately the core test6 is a large discharge of the battery. Who has the same?

**Comment by Spookcity** [comment] 2017-05-24 12:41
@Oleggluk Very strange. I haven't really noticed this. The only reason would be the 1500mhz CPU frequency I think,because that's all I changed from test5.
It was only a few changed lines of code as well to unlock those frequencies as Samsung already has them there. It was just a matter of getting them to be used. I'll keep an eye on my battery life.

Edit:
I enabled zzmoove's input boosters as well,but I'm pretty sure I did that for test5

**Comment by ghost** [comment] 2017-05-25 07:27
You mentioned adding 1.6 or even 1.7 GHz to this kernel, but I was wondering how high this thing can go? 
I'd like to test basically anything, even if it's untested, since I am willing to do everything that improves performance, even if it's at cost of battery life.

**Comment by AshVo925** [comment] 2017-05-25 08:04
I second StanNL,now that I'm accustomed to this rom I would love pushing it to its limits,battery life isn't much of an issue for me either.. oh btw,which kernel for AICP anybody recommends?

**Comment by Spookcity** [comment] 2017-05-25 08:33
@StanNL and @AshVo925 I'm unsure how far it will go. I would assume 1800 would be the max. Doesn't mean it would be stable at all though. I am going to try and see though. Sadly,I have time now and was planning on it,but an open SSL update completely broke my arch Linux,so now I need to spend this time hopefully fixing this. Oh how I love and hate arch lol

**Comment by ghost** [comment] 2017-05-25 12:12
@AshVo925 Well, there's only one kernel for AICP (of any other Nougat ROM), which is Spookcity's kernel!

**Comment by ghost** [comment] 2017-05-25 12:16
@Spookcity 1.8 GHz would actually be pretty decent for a modern phone. So if you could ever make that possible for our device, that would be awesome! I have no clue how Linux works (on PCs), so I wish you the best of luck with resolving your issues, since I won't be of much help

**Comment by AshVo925** [comment] 2017-05-25 12:18
Lol sorry I completely misunderstood my own words there,I would love to max out my phone is all StanNL,thanks for pointing out my mistake and thanks for all the hard work Spookcity, I'll try to test as much an assist you all in any way I can😅

**Comment by ghost** [comment] 2017-05-25 12:21
@AshVo925 Well, I was able to completely understand your comment, but with my comment, I was referring to your last sentence:

> By the way, which kernel for AICP anybody recommends?

**Comment by Spookcity** [comment] 2017-05-25 12:43
@StanNL Thanks, I will try my best. I hope it will work and be relatively stable as well. As far as my Arch Linux problem,luckily I have 3 partitions my root,home and a separate one I that keep ROM sources on. I had to completely reinstall the OS,which is annoying,but I haven't lost much thankfully. Now I just need to get things setup...again.

**Comment by Oleggluk** [comment] 2017-05-26 13:16
I'm waiting for the kernel test 7 with new security patches from hennymcc)
https://forum.xda-developers.com/showpost.php?p=72437401&postcount=807

**Comment by Spookcity** [comment] 2017-05-26 14:56
@Oleggluk Yeah, I've been talking to him about this. His work on our device is to really be commended. Where would we be without him?!I I will try to get these patches in my kernel soon. I hope it is not a big problem to do so.

**Comment by ghost** [comment] 2017-06-02 15:54
Now that the Firefox issue has been resolved, we can start looking into the Chrome issue ;)
Am I the only one who gets an _Aw snap!_ message when trying to display a website with Chrome? It only happens after flashing this kernel. I'm using LiquidROM at the moment and I have not tried this with other ROMs, although I know someone has had this issue before.

_Sent from my Samsung kminilte using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Spookcity** [comment] 2017-06-02 16:21
@StanNL  Haha,incredible. What's funny is that I don't even use Firefox. I use Chrome dev,but haven't tried to use it due to trying to figured out the problem with FF.
Either way,you are correct. There's a problem with all versions of Chrome. A strange new bug. I'll look into it. 

Edit:
Well,I can confirm that the Chrome issue is only with this kernel. Chrome works fine with only the patch to fix FF,ETC. So it must be a build flag or the toolchain I guess. There's not a whole lot more I've changed that would cause this. I'll try to debug it some tonight.
I would really like to hear from anyone who had the fingerprint reboot problems on Lineage though. My tests seemed to indicate it's fixed,but would live to hear from someone else on this.

Edit II:
As suspected it is a build flag that breaks chrome now,oddly. Shouldn't be too difficult to figure out.
_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Oleggluk** [comment] 2017-06-02 18:24
@Spookcity Kernel test8 fingerprints work as before, bootloop no. Firmware RR.

**Comment by Spookcity** [comment] 2017-06-02 18:47
@Oleggluk Thank you for the feedback!

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Spookcity** [comment] 2017-06-02 20:59
Updated the download link for [Test8](https://github.com/Spookcity/ROMS-G800F/issues/10#issuecomment-305805031) Chrome is fixed. The strict aliasing flag now breaks Chrome apparently.

**Comment by ghost** [comment] 2017-06-03 09:15
@Spookcity Thanks! It works again!

_Sent from my Samsung kminilte using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Spookcity** [comment] 2017-06-03 09:41
@StanNL Yes,I'm glad as well because the only browser I use is Chrome. I had just been using Firefox for test purposes and hadn't tried Chrome with the latest updates as the last thing I thought was it would be broken :D

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Oleggluk** [comment] 2017-06-04 08:45
I can not delete the system applications through the special software for this. I can not even edit build.prop, changes are not saved. Root magic.su, core test8, firmware RR, changed the different regimes of selinux. Is there anyone else who has such problems?

**Comment by ghost** [comment] 2017-06-04 09:08
@Oleggluk That issue sure sounds strange. I'd say that the issue lies within the fact that your system directory was not mounted correctly, but I'm not sure

**Comment by Spookcity** [comment] 2017-06-04 09:24
@Oleggluk Weird problem indeed. I would have to agree with @StanNL on this. I can't really think of any other reason. I don't think its an SELinux issue. I could be wrong though.

**Comment by Spookcity** [comment] 2017-06-13 09:45
Just a little "teaser"
![screenshot_20170613-114041](https://user-images.githubusercontent.com/15154102/27076539-cab80e58-502d-11e7-9aad-309f98525243.png)

**Comment by Oleggluk** [comment] 2017-06-13 09:47
@Spookcity When will we test?)

**Comment by Spookcity** [comment] 2017-06-13 10:03
@Oleggluk Not sure yet. I'm going to probably release test9 as v1 on XDA this week if I have the time. Then I may post up a OC build on here for feedback. I have tweaked the voltages,with many thanks to DJSteve for being able to see what he did so not to destroy my phone. I've been using it set at 1.7ghz for almost 2 days now and haven't had a single issue....so far.
Or maybe I release an OC build on here for feedback,then release that as v1. Can you tell I'm unsure? haha
Stay tuned, maybe I'll build and let the OC kernel be tested.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Oleggluk** [comment] 2017-06-13 10:11
@Spookcity I think the version with 1.7ghz is better left as a Test. If everything goes well, you can release V1. I correctly understood, will control voltage? I've been waiting for this feature for so long. Already want to experience)

**Comment by Spookcity** [comment] 2017-06-13 10:17
@Oleggluk I tend to agree with that. I've adjusted the voltages to (hopefully) allow the 1.7 OC to be stable. I've yet to implement the allowing of adjusting them though. Soon it will come though (I hope) 

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Oleggluk** [comment] 2017-06-20 18:35
@Spookcity Above we somehow discussed the error "Battery stats service no controller energy info supplied." The conversation was about the power_profiles.xml file. I was looking at the changes in the RR https://github.com/ResurrectionRemix/android_frameworks_base/commit/bf079b8f29c92669b3e677e80ab402b9b9c64453
Is it interconnected? Or is it quite another.

**Comment by Spookcity** [comment] 2017-06-20 18:50
@Oleggluk It is possible,but I'll be honest I'm really not sure. I do tend to think this has something to do with the way ROMS implement their power profiles as opposed to being kernel related, but I also could be wrong. This is really just a guess.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Guntzog** [comment] 2017-06-20 22:22
@Spookcity a flashed your test13 on RR and the battery became surprisingly poor, so damn fast drain, @Oleggluk have experienced something similar?


_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Spookcity** [comment] 2017-06-21 05:29
@Guntzog Very strange. I don't see why this would be the case. Your battery life should actually improve,at least a little as I've tweaked and patched some things. My battery life is better with it. Either way,I've been working on the kernel a lot and there are many changes since test13. I plan to release it on XDA today or tomorrow hopefully. Then will get a test version up here with some new additions and changes.

**Comment by Oleggluk** [comment] 2017-06-21 07:07
@Guntzog My battery is 2.5 years from the date of purchase. Works badly already. It is difficult for me to judge the expenditure of energy. I also always use the core of Spookcity and I do not know how much power is consumed on the original core. I ordered a new battery.

**Comment by Guntzog** [comment] 2017-06-21 11:24
@Spookcity waiting for the kernel !

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jimmy999x** [comment] 2017-07-29 00:21
![screenshot_2017-07-28-19-17-46](https://user-images.githubusercontent.com/21678167/28740391-85398674-73da-11e7-84e3-88c1c1be8714.png)
I can not install version 3.0a of your kernel, I know how to correct that, I need to make the boot image a little bigger and re compile liquidark rom, in a few days it will be ready

**Comment by Spookcity** [comment] 2017-07-29 08:03
Hmm,interesting. Thanks for the heads up. I've only flashed this version on AOKP and AICP. I'm not sure why this issue though. I had this problem when I tried to use LZ4 compression for the kernel. I'm still looking into that. I think the boot image partition for our device is actually larger than what is in the fstab. I'm not positive though. Let me know the outcome of this though.

**Closed as completed** 2020-01-11 00:07 UTC
